language: haskell
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y aspell aspell-en
    - sudo apt-get install -y arduino-core
install:
    - cabal install mtl
    - git clone https://github.com/sudar/Arduino-Makefile.git
script:
    - ./test
